# serverless.yml 
service: my-service
provider:   
  name: aws   
  runtime: nodejs6.10
functions:
  hello:
    handler: handler.hello
    events: # uncomment these lines
      - http:
          path: hello/get
          method: get
		  
# adding these two lines
plugins:
  - serverless-offline		  
			